In [287]:
import numpy as np

In [288]:
arr = np.random.randint(1,10, size = (5,5)) #random하게 정수를 뽑아냄 
arr

array([[7, 9, 9, 2, 7],
       [8, 8, 9, 2, 6],
       [9, 5, 4, 1, 4],
       [6, 1, 3, 4, 9],
       [2, 4, 4, 4, 8]])

In [289]:
arr.T
np.transpose(arr)

array([[7, 8, 9, 6, 2],
       [9, 8, 5, 1, 4],
       [9, 9, 4, 3, 4],
       [2, 2, 1, 4, 4],
       [7, 6, 4, 9, 8]])

In [290]:
#행렬곱, 내적
np.dot(arr.T,arr)

array([[234, 186, 197,  71, 203],
       [186, 187, 192,  59, 172],
       [197, 192, 203,  68, 192],
       [ 71,  59,  68,  41,  98],
       [203, 172, 192,  98, 246]])

In [291]:
a = np.arange(6).reshape(2,3)
print(a,'\n')

y = np.swapaxes(a,0,1) #0은 2차원 (열). 1은 1차원 (행)
print(y)

print('\n',a.T)


y = np.transpose(a)
print('\n',y)

[[0 1 2]
 [3 4 5]] 

[[0 3]
 [1 4]
 [2 5]]

 [[0 3]
 [1 4]
 [2 5]]

 [[0 3]
 [1 4]
 [2 5]]


In [292]:
[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]] 


SyntaxError: invalid syntax (Temp/ipykernel_5424/1238534767.py, line 1)

In [ ]:
arr= np.arange(1,11)
print(arr1)
arr2 = np.arange(11,21)
print(arr2.T)
arr3= np.arange(21,31)
print(arr3)
arr4= np.arange(31,41)
print(arr4.T)
arr5= np.arange(41,51)
print(arr5)
arr6= np.arange(51,61)
print(arr6.T)


In [ ]:
arr= np.arange(1,101).reshape(10,10)
print(arr1)


In [ ]:
print(arr1[1][::-1])
print(arr1[3][::-1])

In [ ]:
arr = np.arange(1,101).reshape(10,10)
arr[[1,3,5,7,9]] = arr[[1,3,5,7,9]][:,::-1]
print(arr)


In [ ]:
# (0,1,2) 0->3차원,1->2차원,2->1차원
#3차원과 2차원을 바꾸는 경우: (1.2,3) - > (2,1,3)

a = np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')

y =np.transpose(a,(1,0,2))
print(y,y.shape)

In [ ]:
#(1,2,3) - > (2,3,1)
a = np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')
y = np.transpose(a,(1,2,0))
print(y,y.shape)

In [ ]:
#[과제] 아래 배열에서 3차원과 2차원을 변경하여 출력하세요 (shape확인)
arr = np.arange(16).reshape(2,2,4)
print(arr,arr.shape,'\n',arr.ndim,'\n')

arr1 = arr.reshape(2,-1)
print(arr1,arr1.shape,arr1.ndim)

In [ ]:
#[과제] 상기 과제의 arr 에서 2차원과 1차원을 변경하여 출력하세요

arr2 = arr1.reshape(-1,)
print(arr1,arr2.shape,arr2.ndim)

In [ ]:
# 나머지를 구할 경우 사용하는 함수
value1 = np.array([15,30,45])
value2 = np.array([2,7,9])
print(np.mod(value1,value2))
print(np.remainder(value1,value2))


In [ ]:
#각 수의 역수를 구해주는 함수  #0.85분의 1,  1.85분의 1해준거
value = np.array([0.85,1.85,1,100])
print(np.reciprocal(value))


value1 = np.array([100],dtype = int)
print(value1,'\n')
print(np.reciprocal(value1,dtype =float))

In [ ]:
#승수의 결과 값을 표시해주는 함수 : power
value1 = np.array ([2,10,15])
value2 = np.array([1,2,3])

print(np.power(value1,2),'\n')
print(np.power(value1,value2))

In [ ]:
arr = np.random.randn(10)     #-4.ddddde-05(소수점 5개 더 있단 뜻)
# print(arr.mean(),'\n')
# print(arr.std())
arr

In [ ]:
#양수인 원소의 개수
(arr>0).sum()


In [ ]:
#하나 이상의 값이 True인지 검사
bools = np.array([False,False,True,True])
bools.any()

In [ ]:
#모든 원소가 True인지 검사
bools.all()

In [ ]:
# 삼항식의 벡터화 버전
arr= np.random.randn(4,4)
print(arr,'\n')
np.where(arr>0,2,-2 ) #0보다 크면 2, 아니면 -2

In [ ]:
#arr의 모든 양수를 2로 바꿀 경우
arr= np.random.randn(4,4)
np.where(arr>0,2,arr) # 아닌 경우 그냥 기존의 arr 로 주면 됨

In [ ]:
# 두개의 1차원 배열을 받아서 가능한 모든 (x,y) 짝을 만들 수 있는 2차원 배열
#2개 반환
x = np.arange(1,4)
y = np.arange(1,4)
xs,ys = np.meshgrid(x,y)
print(xs, ' \n')
print(ys)

In [ ]:
#np.sort()
np.random.seed(0)
arr = np.random.randint(1,100,size = 10)
print(arr,'\n')
print(np.sort(arr),'\n')  # np.sort()는 원본반영 x
print(arr)
    


In [ ]:
sorted = np.sort(arr)
print(sorted)
print(arr)

In [ ]:
#행렬이 2차원 이상일 떄 axis 축 값 설정을 통해 행, 열 방향으로 정렬 수행
arr2d = np.array([[8,12],[7,1]])
print(arr2d,'\n')
sort_ar2d_axis0 = np.sort(arr2d,axis=0) #정렬을 했는데 axis= 0(행방향으로) 정렬
print(sort_ar2d_axis0,'\n')
sort_ar2d_axis1 = np.sort(arr2d,axis=1)# 열 방향이니깐 
print(sort_ar2d_axis1)

In [ ]:
# ndarray.sort():원본반영
np.random.seed(0)
arr = np.random.randint(1,10,size = 10)
print(arr,'\n')
arr.sort()  #원본반영 바뀜
arr

In [ ]:
# 다차원 배열의 정렬은 sort 메소드에 넘긴 축에 따라 1차원 부분을 정렬
#열방향 - default
np.random.seed(0)
arr = np.random.randint(1,10,size = (5,3))
print(arr,'\n')
arr.sort(1)  #열방향
print(arr)

In [ ]:
#행방향 정렬
np.random.seed(0)
arr = np.random.randint(1,10,size = (5,3))
print(arr,'\n')
arr.sort(0)  #행방향
print(arr)

In [ ]:
#정렬된 행렬의 인덱스 반환: 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때
#argsort 는 배열정렬 후 인덱스 값 반환
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(org_array)
print(type(sort_indices))
sort_indices

In [ ]:
# 배열에서 정렬한 후 5%에 해당하는 요소(분위수) 출력
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05*len(large_arr))]
#1000개 잖아 곱하기 *0.05하면 50개 int를 붙인거고 large_arr[조건]

In [ ]:
#배열 집합 연산
names = np.array(['Bob','Joe','Will','Joe','Joe'])
np.unique(names)

In [ ]:
names = np.sort(names)
names

In [ ]:
import numpy as np
names = np.array(['Bob','Joe','Will','Joe','Joe'])
sorted(set(names))

In [ ]:
#첫번쨰 배열의 원소가 두번쨰 배열의 원소를 포함하는지 알려주는 불리언 배열을 빈환
values = np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6])



In [ ]:
#배열 데이터의 입출력
#np.save, np.load는 바이너리 형식으로 .npy파일로 저장
arr = np.arange(10)
np.save('some_array',arr)


In [ ]:
np.load('some_array.npy')

In [ ]:
#np.savez : 여러개의 배열을 압축된 형식으로 저장
np.savez('array_archive.npz',a=arr,b=arr)


In [ ]:
arch= np.load('array_archive.npz')
arch['b']
arch['a']



In [ ]:
#Q.인덱싱을 사용하여 [1 0 1 0 1 0 1 0 1 0]을 출력하세요
a = np.ones(10,dtype=int)
a[[1,3,5,7,9]]=0   #인덱스를 줘서 0 집어넣어주면 되지 
a

In [ ]:
# Q. a = np.arange(10)에서 [6,7,8,9] 출력
a = np.arange(10)
print(a[6:10])

In [ ]:
#Q. a에서 최대값, 최소값 인덱스 출력
a= np.arange(1,10)
print(np.argmax(a))
print(np.argmin(a))

In [ ]:
#Q. a에서 인덱스 배열을 역순으로 출력하세요
print(a[::-1])

In [ ]:
np.argsort(a)[::-1]

In [ ]:
# Q. np.omes((10,10))을 아래와 같이 출력하세요
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [ ]:
arr = np.ones((10,10))
arr[1:9,1:9]=0 
arr

In [ ]:
arr = np.arange(1,101).reshape(10,10)
arr[[1,3,5,7,9]] = arr[[1,3,5,7,9]][:,::-1]
print(arr)

In [ ]:
#[과제]  np.ones를 ((5,5))을 아래와 같이 출력하세요

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [352]:
five = np.ones((5,5))
arr = np.zeros((10,10))
arr[2:7,2:7] = 1
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#[과제]np.ones((8,8))을 이용해서 아래와 같이 추력하세요(인덱싱,tile함수())

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])


In [386]:
import numpy as np
a= np.array([[0,1],[1,0]])
b= np.tile(a,(4,4))
b


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [397]:
np.eye(8)
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
#[도전과제] np.arange(336),reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요

In [ ]:
#[도전과제] np.arrange(4)을 이용해서 아래와 같이 출력하세요
array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])


###[파이썬 random 함수]


In [ ]:
import random
print(random.random(),'\n') #0.0 <= x < 1.0 사이
print(random.randint(1,10),'\n') #1에서 10사이의 정수중에서 난수 값 리턴
print(random.uniform(10,20),'\n') #min,max사이 float리턴 
print(random.randrange(10),'\n') # 지정범위 int리턴
print(random.choice([1,2,3,4,5]),'\n') #리스트 내부에 있는 요소를 랜덤하게 선택

li= [1,2,3,4,5]
print(random.sample(li,3),'\n')#리스트 요소를 중복이 안되게 리턴
random.shuffle(li) #리스트 요소를 다시 섞어서 리턴
print(li)

### [numpy_random함수]

- np.random.seed  : seed를 통한 난수 생성
- np.random.randint : 균일분포의 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기 
- np.random.choice : 기존 데이터에서 sampling 

In [ ]:
print(np.random.randint(6), '\n') # 0에서 5까지 정수인 난수 1개 
print(np.random.randint(1,20),'\n') # 1~19까지 정수인 난수 1개
print(np.random.randint(10,size = 10), '\n') # 0~ 9까지 정수인 난수 10개
print(np.random.randint(10,20, size = 10), '\n')# 10에서 10까지 정수인 난수10개
print(np.random.randint(10,20, size = (3,5))) # 10 에서 19까지 정수인 난수로 3행5열


In [ ]:
r = np.random.rand(6) # 0~ 1 사이의  균일분포 함수 (rand)
print(r,'\n')

r.mean() #평균값

In [ ]:
#표준 정규분포 평균 0과 표준편차 1 사이에 가우시안 정규분포 난수 생성
r = np.random.randn(6)
r

#균일분포는 미래의 결과값을 예측할 수 없을 떄
like : 주사위 던지면 나올 수 있는 결과값이 1~6까지 중 랜더믕로 나오는데 201번째
    라해도 200번째까지 전혀 영향을 미치지않지
but 정규분포값은 어느정도 예측이 가능함, 6개월치 데이터를 가지고 7월의 
예상매출액을 낼수있듯

In [ ]:
#기존의 데이터 숫자 바꾸는 suffle
list = np.arange(1,6)
print(list,'\n')
np.random.shuffle(list)
list

In [ ]:
np.random.choice(list)

In [ ]:
a = np.array([11,11,3,3,2,2,2,7])
index,count = np.unique(a,return_counts = True)
print(index)
print(count)

In [ ]:
np.random.uniform(1.0,2.0, 10)


In [ ]:
print(np.random.uniform(0,1,(2,3)))

In [ ]:
#0~1 사이의 난수 실수값으로 행렬 생성 
#uniform 함수의 최소값, 최대값을 각각 0,1로 지정한 것과 같음
np.random.random_sample((2,3))

In [ ]:
!pip install pandas

In [305]:
ar = np.random.rand(4,8)
ar


array([[0.96541622, 0.58846509, 0.65966841, 0.53320625, 0.23053302,
        0.39486929, 0.61880856, 0.47486752],
       [0.47013219, 0.71607453, 0.287991  , 0.38346223, 0.74916984,
        0.87845219, 0.10286336, 0.09237389],
       [0.35404666, 0.55181626, 0.03362509, 0.96896177, 0.32099724,
        0.22126269, 0.1412639 , 0.09725993],
       [0.98404224, 0.26034093, 0.53702252, 0.44792617, 0.09956909,
        0.35231166, 0.46924917, 0.84114013]])

In [306]:
# 배열을 데이터프레임으로 변환
import pandas as pd
df = pd.DataFrame(ar)
print(df,type(df))

          0         1         2         3         4         5         6  \
0  0.965416  0.588465  0.659668  0.533206  0.230533  0.394869  0.618809   
1  0.470132  0.716075  0.287991  0.383462  0.749170  0.878452  0.102863   
2  0.354047  0.551816  0.033625  0.968962  0.320997  0.221263  0.141264   
3  0.984042  0.260341  0.537023  0.447926  0.099569  0.352312  0.469249   

          7  
0  0.474868  
1  0.092374  
2  0.097260  
3  0.841140   <class 'pandas.core.frame.DataFrame'>


In [ ]:
print(df [0])
type(df[0])

In [ ]:
#Q. id, gender,age 컬럼에 대하여 의미있는 값으로 변환하여 3개의 컬럼으로
#구성된 df를 출력하세요
columns = ['id','gender','age','region','product','price','qty','time']
index = [np.arange(4)]  # 0,1,2,3이란거죵
df = pd.DataFrame(ar,index, columns = columns) #colums를 리스트로 ㅏ만들어 출력
df

In [ ]:
ar = np.zeros((4,3))  
columns = ['id','gender','age']
index = [np.arange(4)] 
df = pd.DataFrame(ar,index, columns = columns) #colums를 리스트로 ㅏ만들어 출력
np.random.seed(0)
df.id = np.random.randint(0,1000,size=4)
df.age = np.random.randint(0,100,4)
df.gender = np.random.choice(['F','M'],4)
df

In [ ]:
ID = np.random.randint(1000,10000,3)
gen = np.random.choice(['M','F'],3)
age = np.random.randint(10,40,3)

data = np.array([ID,gen,age]).reshape(3,3).transpose()
df=pd.DataFrame(data,np.arange(1,4),['ID','Gender','Age'])
df


In [ ]:
h = np.zeros((3, 10))
id_ = np.random.randint(1, 1000, size = (1, 10))
gender = np.random.randint(2, size = (1, 10))
age = np.random.randint(0, 120, size = (1, 10))

h[0] = id_
h[1] = gender
h[2] = age

h = np.transpose(h)

columns = ['id', 'gender', 'age']
index = np.arange(1, 11)
df = pd.DataFrame(h, index, columns = columns)

df


###[과제] 아래 가이드에 따라서 고객 구매데이터를 생성하고 데이터 프레임으로 변혼하여 출력
 - id : 1 ~ 1000번 일련번호
 - gender : 0,1 정수 난수 생성
 - age : 0 ~ 80사이 정수 난수 생성
 - region : 1 ~ 10 사이 정수 난수 생성
 - product_19 : 제품코드 11111 ~ 99999
 - product_20 : 제품코드 11111 ~ 99999
 - price_19 : 1000 ~ 50000 사이 실수 난수 생성
 - price_20 : 1000 ~ 50000 사이 실수 난수 생성
- quantity_19 : 1 ~ 100 사이 정수 난수 생성
- quantity_20 : 1 ~ 100 사이 정수 난수 생성
- time_19 : 01 ~ 24 사이 정수 난수 생성
- time_20 : 01 ~ 24 사이 정수 난수 생성
- amount_19 : price_19 * quantity_19
- amount_20 : price_20 * quantity_20
- sales : 19년 대비 20년구매금액이 증가면 1, 감소면 0

In [336]:
ar = np.random.rand(1000,15)
ar

array([[0.84960398, 0.55679452, 0.21364467, ..., 0.65959773, 0.26215945,
        0.51713677],
       [0.3391828 , 0.92420744, 0.06388845, ..., 0.62965987, 0.84340933,
        0.58117938],
       [0.35753836, 0.04058937, 0.95838967, ..., 0.17219011, 0.10678606,
        0.36485542],
       ...,
       [0.96190259, 0.31314971, 0.54061375, ..., 0.25587552, 0.67518975,
        0.46065692],
       [0.77285989, 0.39801204, 0.1217915 , ..., 0.41353601, 0.6832142 ,
        0.4864349 ],
       [0.91084928, 0.38865189, 0.47725768, ..., 0.91809638, 0.43340167,
        0.78128967]])

In [396]:
import pandas as pd
columns =['id','gender','age',
          'region','product_19','product_20','price_19','price_20','qty_19',
          'qty_20','time_19','time_20','amount_19','amount_20','sales']

index = [np.arange(0,1000)]  
df = pd.DataFrame(ar,index, columns = columns)
np.random.seed(0)
df.id = np.random.randint(1,1000,size=1000)
df.age = np.random.randint(0,80,1000)
df.region = np.random.randint(0,10,1000)
df.gender = np.random.randint(2,size=1000)
df.product_19 = np.random.randint(11111,99999,size=1000)
df.product_20 = np.random.randint(11111,99999,size=1000)
df.price_19 = np.random.randint(1000,50000,size=1000)
df.price_20 = np.random.randint(1000,50000,size=1000)
df.qty_19 = np.random.randint(1.0,100.0,size=1000)
df.qty_20 = np.random.randint(1.0,100.0,size=1000)
df.time_19 = np.random.randint(1,24,size=1000)
df.time_20 = np.random.randint(1,24,size=1000)
df.amount_19 = df.price_19*df.qty_19
df.amount_20 = df.price_20*df.qty_20
df.sales = np.where(df.amount_19<df.amount_20,'1','0')
df.head(11)

id  gender  age  region  product_19  product_20  price_19  price_20  \
0   685       1    0       4       33190       78414     31594     21035   
1   560       1   66       7       61331       20014     10956     10067   
2   630       1   12       0       95972       17188     42069     10681   
3   193       1   15       3       42473       72327     48693     22352   
4   836       0   33       5       88445       46468     32614     38756   
5   764       0   23       6       35043       80646     15567     40204   
6   708       0   12       6       49919       32054     18657     21452   
7   360       0    5       7       92947       53810     44209     24761   
8    10       0   38       4       35514       75602     39782     47753   
9   724       1    1       7       43589       55558      9203     38800   
10  278       0   10       2       49972       26578     17190     39312   

    qty_19  qty_20  time_19  time_20  amount_19  amount_20 sales  
0        1      28       21       15      31594     588980     1  
1       54      76       18       14     591624     765092     1  
2       75      60        5       11    3155175     640860     0  
3        4      48        7        2     194772    1072896     1  
4       66      48       22        7    2152524    1860288     0  
5       26      87       10        9     404742    3497748     1  
6       13      33       18        7     242541     707916     1  
7       61      54        1        9    2696749    1337094     0  
8       75       5       16       22    2983650     238765     0  
9       58      30       19       18     533774    1164000     1  
10      23      38       12       18     395370    1493856     1