## 판다스
- 판다스는 구조화된 데이터 형식을 제공, 시리즈는 1차원 배열, 데이터프레임은
 2차원 배열
- 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. 시리즈와 데이터프레임은
대표적인 클래스 객체임
- 라이브러리 패키지>모듈>클래스>함수
- 시리즈 인덱스는 데이터값과 일대일 대응, 파이썬 딕셔너리와 비슷한 구조.
- pandas.Series(딕셔너리)
- Series(변환, 인덱스 구조, 원소 선택)
- DataFrame(변환, 인덱스,삭제,선택,추가,변경,전치 등 )



In [5]:
# 딕셔러니를 시리즈로 변환
import pandas as pd

dic_data={'a':1,'b':2,'c':3}
sr = pd.Series(dic_data)
print(sr,type(sr))

a    1
b    2
c    3
dtype: int64 <class 'pandas.core.series.Series'>


In [7]:
#리스트를 시리즈로 변환
list_data = ['2019-10-02',3.14,'ABC',100, True]
sr = pd.Series(list_data, index = ['a','b','c','d','e'])
sr

a    2019-10-02
b          3.14
c           ABC
d           100
e          True
dtype: object

In [17]:
idx = sr.index
print(idx,'\n')
val = sr.values
print(val)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object') 

['2019-10-02' 3.14 'ABC' 100 True]


In [29]:
# 튜플을 시리즈로 변환
tup_data = ('영인','2015-05-01','여',True)
sr= pd.Series(tup_data,index = ['이름','생년월일','성별','학생여부'])
sr

이름              영인
생년월일    2015-05-01
성별               여
학생여부          True
dtype: object

In [57]:
print(sr[0])
print(sr['이름'],'\n')

print(sr['생년월일':'성별'],'\n')
print(sr['생년월일':'학생여부'],'\n')
print(sr[[1,3]],'\n')
print(sr[1:3])

영인
영인 

생년월일    2015-05-01
성별               여
dtype: object 

생년월일    2015-05-01
성별               여
학생여부          True
dtype: object 

생년월일    2015-05-01
학생여부          True
dtype: object 

생년월일    2015-05-01
성별               여
dtype: object


In [62]:
#배열을 시리즈로 변환
import numpy as np
s1 = np.arange(start = 11, stop =16)
s2 = pd.Series(s1,index = ['ED1','ED2','ED3','ED4','ED5'])
print(s1,type(s1),'\n')
print(s2,type(s2),'\n')

[11 12 13 14 15] <class 'numpy.ndarray'> 

ED1    11
ED2    12
ED3    13
ED4    14
ED5    15
dtype: int32 <class 'pandas.core.series.Series'> 



In [79]:
print(s2[1:3],'\n')
print(s2['ED2':'ED3'],'\n')
print(s2[[1,3]],'\n')
print(s2[['ED2','ED4']])

ED2    12
ED3    13
dtype: int32 

ED2    12
ED3    13
dtype: int32 

ED2    12
ED4    14
dtype: int32 

ED2    12
ED4    14
dtype: int32


In [82]:
#시리즈 -> 배열
print(type(s2))
ar = np.array(s2)
print(ar,type(ar))

<class 'pandas.core.series.Series'>
[11 12 13 14 15] <class 'numpy.ndarray'>


In [109]:
# Q. 4가지 자료형 데이터를 생성하고 각각 시리즈로 변환하여 출력하세요

listdata=['ABC','DEF',True,'이현정',25]

sr = pd.Series(listdata,index = ['a','b','c','d','e'])
print(sr,'\n')

tupledata=('abc','def')
sr = pd.Series(tupledata,index = ['a','b'])
print(sr,'\n')

dicdata = {'ab':1,'bd':2}
sr= pd.Series(dicdata)
print(sr,'\n')

import numpy as np
arr = np.arange(1,3)
sr = pd.Series(arr,index= ['a','b'])
print(sr,'\n')

a     ABC
b     DEF
c    True
d     이현정
e      25
dtype: object 

a    abc
b    def
dtype: object 

ab    1
bd    2
dtype: int64 

a    1
b    2
dtype: int32 



In [105]:
lidata = [2,3,4,5]
tudata = (True,False,True,True)
dicdata = {'김첨지':'설렁탕','점순이':'감자','나':'아달린'}
arrdata = np.array(['살바도르','빈센트','파블로','램브란트'])
index = ['1번','2번','3번','4번']

li = pd.Series(lidata,index)
tu = pd.Series(tudata,index)
dic = pd.Series(dicdata)
arr = pd.Series(arrdata,index)

print(li,'\n',tu,'\n',dic,'\n',arr)


1번    2
2번    3
3번    4
4번    5
dtype: int64 
 1번     True
2번    False
3번     True
4번     True
dtype: bool 
 김첨지    설렁탕
점순이     감자
나      아달린
dtype: object 
 1번    살바도르
2번     빈센트
3번     파블로
4번    램브란트
dtype: object


In [113]:
data = np.arange(1000,5000,1000)
obj = pd.Series(data)
state = ['California','Ohio','Oregon','Texas']
obj.name= 'population'
obj.index = state
obj.index.name = 'state'
obj

state
California    1000
Ohio          2000
Oregon        3000
Texas         4000
Name: population, dtype: int32

In [115]:
obj.California = np.nan
obj

state
California       NaN
Ohio          2000.0
Oregon        3000.0
Texas         4000.0
Name: population, dtype: float64

In [123]:
obj['California']

nan

In [118]:
#is null 널이 있느냐 있는 건 트류/ 거기다 sum까지 하면 튜르 갯수 세줌
obj.isnull().sum()

1

In [134]:
#처음 만들 때는 대괄호 해줘야됨
obj['Newyork'] = 3000
obj

state
California       NaN
Ohio          2000.0
Oregon        3000.0
Texas         4000.0
Newyork       3000.0
Name: population, dtype: float64

## 데이터프레임 
- 데이터프레임은 2차원 배열. R의 데이터프레임에서 유래
- 데이터프레임은 열은 각가 시리즈 개체
- 시리즈를 열벡터하고 하면 데이터 프레임은 여러개의 열벡터들이 같은행 인덱스를
 기준으로 줄지어 결합된 2차 벡터 또는 행렬
- 선형대수학에서 열 벡터(mx1행렬)는 m원소들의 단일 열 행렬
- 행 벡터(1*m 행렬)은 m원소들의 단일 행 행렬
- 리스트, 딕셔너리,배열 등 다양한 데이터로부터 생성
- 반대로 리스트, 딕셔너리, 배열 등으로 변환될 수 있다


In [145]:
#배열 -> 데이터프레임

ar = np.random.randint(100,120,size =(3,3))
print(ar,type(ar),'\n')
df = pd.DataFrame(ar,index = ['d1','d2','d3'],
                  columns=['pd','sales','int'])

df

[[103 104 116]
 [105 114 112]
 [103 107 118]] <class 'numpy.ndarray'> 



pd  sales  int
d1  103    104  116
d2  105    114  112
d3  103    107  118

pandas indexing
- iloc : integer localition의 약어, 데이터프레임의 행이나 칼럼의 순서를 나타내는
    정수로 특정 값을 추출해오는 방법
- loc : 인덱스명,칼럼명을 직접 적거나 특정조건식을 써줌으로써 사람이 읽기 좋은 방법으로 데이터에
     접근하는 방법

In [158]:
#  행선택
df.iloc[1,1]
df.iloc[0]

pd       103
sales    104
int      116
Name: d1, dtype: int32

In [169]:
df.loc['d2']

pd       105
sales    114
int      112
Name: d2, dtype: int32

In [178]:
#특정 행, 열 선택
print(df.iloc[1,1],'\n')
print(df.loc['d2','sales'])


114 

114


In [180]:
#행 추가
df1 = df.copy()
df1.loc['d5']= 0
df1


pd  sales  int
d1  103    104  116
d2  105    114  112
d3  103    107  118
d5    0      0    0

In [191]:
#열 추가
df1['pf']=[100,100,100,0]
df1

pd  sales  int   pf  d6
d1  103  104.0  116  100   0
d2  105    NaN  112  100   0
d3  103  107.0  118  100   0
d5    0    0.0    0    0   0

In [200]:
#이미 지워서 안뜨는데 열 삭제할 땐 axis=1 반드시 줘야됨, 행은 기본값
df1.drop('d6',axis=1,inplace =True)
df1

KeyError: "['d6'] not found in axis"

In [184]:
#원소 값 변경

df1.iloc[1,1]=np.nan
df1

pd  sales  int
d1  103  104.0  116
d2  105    NaN  112
d3  103  107.0  118
d5    0    0.0    0

In [213]:
#사전 - > 데이터프레임
sp1 = np.arange(1,6)
df = pd.DataFrame({
    'col1': sp1,
    'col2': sp1 *2,
    'col3':['A','B','C','D','E']
    
})
df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E

In [222]:
#리스트 -> 데이터 프레임
a = np.random.randint(1,5, size = (10,5))
list1 = a.tolist()
list1
df=pd.DataFrame (list1, index, columns=['c1','c2','c3','c4','c5'])
df

c1  c2  c3  c4  c5
1    3   2   1   1   3
2    1   4   3   3   4
3    2   4   2   1   1
4    4   4   4   2   1
5    4   4   4   1   1
6    3   3   4   4   2
7    4   3   4   3   3
8    1   4   4   3   2
9    3   1   1   1   1
10   2   3   3   4   4

In [188]:
df = pd.DataFrame([[14,'남','엄경중'],[18,'여','복덩중']],
                 index = ['준서','예은'],
                 columns =['나이','성별','학교'])

print(df)
print(df.index)
df.index = ['학생1','학생2']
df.rename(columns={'나이':'연령','성별':'남녀','학교':'소속'},inplace=True)
df

    나이 성별   학교
준서  14  남  엄경중
예은  18  여  복덩중
Index(['준서', '예은'], dtype='object')


연령 남녀   소속
학생1  14  남  엄경중
학생2  18  여  복덩중

In [229]:
# 데이터프레임-> 배열, 리스트, 딕셔너리 
ar = df.values 
print(ar,type(ar),'\n')
li = df.values.tolist()
print(li,type(li),'\n')
dict = df.to_dict('list')
print(dict)

[[3 2 1 1 3]
 [1 4 3 3 4]
 [2 4 2 1 1]
 [4 4 4 2 1]
 [4 4 4 1 1]
 [3 3 4 4 2]
 [4 3 4 3 3]
 [1 4 4 3 2]
 [3 1 1 1 1]
 [2 3 3 4 4]] <class 'numpy.ndarray'> 

[[3, 2, 1, 1, 3], [1, 4, 3, 3, 4], [2, 4, 2, 1, 1], [4, 4, 4, 2, 1], [4, 4, 4, 1, 1], [3, 3, 4, 4, 2], [4, 3, 4, 3, 3], [1, 4, 4, 3, 2], [3, 1, 1, 1, 1], [2, 3, 3, 4, 4]] <class 'list'> 

{'c1': [3, 1, 2, 4, 4, 3, 4, 1, 3, 2], 'c2': [2, 4, 4, 4, 4, 3, 3, 4, 1, 3], 'c3': [1, 3, 2, 4, 4, 4, 4, 4, 1, 3], 'c4': [1, 3, 1, 2, 1, 4, 3, 3, 1, 4], 'c5': [3, 4, 1, 1, 1, 2, 3, 2, 1, 4]}


In [ ]:
#Q. 배열, 리스트 딕셔너리로 데이터프레임을 생성한 후 다시 배열, 리스트,
#딕셔너리로 변환하여 출력하세요

In [247]:
arr = np.random.randint(1,6,size=(4,5))
index = np.arange(1,5)
sr = pd.DataFrame(arr, index, columns= ['a','b','c','d','e'] )
sr

arr=df.values
print(arr)


[[3 2 1 1 3]
 [1 4 3 3 4]
 [2 4 2 1 1]
 [4 4 4 2 1]
 [4 4 4 1 1]
 [3 3 4 4 2]
 [4 3 4 3 3]
 [1 4 4 3 2]
 [3 1 1 1 1]
 [2 3 3 4 4]]


In [299]:
#리스트 -> 데이터 프레임
a = np.random.randint(1,5, size = (10,5))
list1 = a.tolist()
list1
index = np.arange(1,11)
df=pd.DataFrame (list1, index, columns=['c1','c2','c3','c4','c5'])
df

c1  c2  c3  c4  c5
1    3   2   2   1   2
2    4   2   3   2   3
3    2   1   3   2   1
4    2   1   4   2   4
5    4   4   4   1   4
6    3   3   2   1   2
7    4   3   4   2   4
8    2   2   4   4   1
9    2   1   1   1   2
10   4   1   4   4   1

In [276]:
lst = ['abc','bd','cd','ed','fe']

index = np.arange(1,6)
df = pd.DataFrame(lst,index,columns = ['ahpa'])
df

lst=df.values.tolist()
lst

[['abc'], ['bd'], ['cd'], ['ed'], ['fe']]

In [298]:


dic = pd.DataFrame({
    '커피': [4000,3000,4000]
    '쿠키':3000,
    '케이크':6500
    },index=['가격'])

    
dic

커피    쿠키   케이크
가격  4000  3000  6500

In [293]:
import warnings
warnings.filterwarnings('ignore')
dict = df.to_dict('list')
dict



{'ahpa': ['abc', 'bd', 'cd', 'ed', 'fe']}

In [296]:
#file생성,저장,읽기
li = ['냉면','콩국수','잔치국수','수제비','우동']
df1 = pd.DataFrame(li,index = ['메뉴1','메뉴2','메뉴3','메뉴4','메뉴5'],columns=['차림표'])
df1.to_csv("./dataset/file_data.csv",index= None)
file_data = pd.read_csv("./dataset/file_data.csv")
file_data

차림표
0    냉면
1   콩국수
2  잔치국수
3   수제비
4    우동

In [301]:
#사전 - > 데이터프레임
sp1 = np.arange(1,6)
df = pd.DataFrame({
    'col1': sp1,
    'col2': sp1 *2,
    'col3':['A','B','C','D','E']
    
})
df

#둘 다 배열이고 리스트

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E

In [305]:
dic= {'A':1,'B':2,'C':3,'D':4}
#여기서 숫자들은 상수
columns = ['a','b','c','d']

df_dic =pd.DataFrame(dic,index)
print(df_dic)



   A  B  C  D
1  1  2  3  4
2  1  2  3  4
3  1  2  3  4
4  1  2  3  4
