In [92]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
movies = pd.read_csv('./dataset/tmdb_5000_movies.csv')
print(movies.shape)
movies.head(2)

(4803, 20)


budget  \
0  237000000   
1  300000000   

                                                                                                genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {...   
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 28, "name": "Action"}]   

                                       homepage     id  \
0                   http://www.avatarmovie.com/  19995   
1  http://disney.go.com/disneypictures/pirates/    285   

                                                                                              keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "sp...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "name": "drug abuse"}, {"id": 911, "name": "exotic is...   

  original_language                            original_title  \
0                en                                    Avatar   
1                en  Pirates of the Caribbean: At World's End   

                                                                                              overview  \
0  In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, ...   
1  Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of t...   

   popularity  \
0  150.437577   
1  139.082615   

                                                                                  production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289}, {"name": "Twentieth Century Fox Film Corporatio...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"name": "Jerry Bruckheimer Films", "id": 130}, {"na...   

                                                                                  production_countries  \
0  [{"iso_3166_1": "US", "name": "United States of America"}, {"iso_3166_1": "GB", "name": "United ...   
1                                           [{"iso_3166_1": "US", "name": "United States of America"}]   

  release_date     revenue  runtime  \
0   2009-12-10  2787965087    162.0   
1   2007-05-19   961000000    169.0   

                                                                        spoken_languages  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso_639_1": "es", "name": "Espa\u00f1ol"}]   
1                                               [{"iso_639_1": "en", "name": "English"}]   

     status                                         tagline  \
0  Released                     Enter the World of Pandora.   
1  Released  At the end of the world, the adventure begins.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500

In [93]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [94]:
movies_df = movies[['id','title','genres','vote_average','vote_count','popularity','keywords','overview']]
movies_df.head()

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   

                                                                                                genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {...   
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 28, "name": "Action"}]   
2         [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 80, "name": "Crime"}]   
3  [{"id": 28, "name": "Action"}, {"id": 80, "name": "Crime"}, {"id": 18, "name": "Drama"}, {"id": ...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 878, "name": "Science Fic...   

   vote_average  vote_count  popularity  \
0           7.2       11800  150.437577   
1           6.9        4500  139.082615   
2           6.3        4466  107.376788   
3           7.6        9106  112.312950   
4           6.1        2124   43.926995   

                                                                                              keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "sp...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "name": "drug abuse"}, {"id": 911, "name": "exotic is...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name": "based on novel"}, {"id": 4289, "name": "secret...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853, "name": "crime fighter"}, {"id": 949, "name": "te...   
4  [{"id": 818, "name": "based on novel"}, {"id": 839, "name": "mars"}, {"id": 1456, "name": "medal...   

                                                                                              overview  
0  In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, ...  
1  Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of t...  
2  A cryptic message from Bond’s past sends him on a trail to uncover a sinister organization. Whil...  
3  Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's c...  
4  John Carter is a war-weary, former military captain who's inexplicably transported to the myster...

In [95]:
movies_df.genres

0       [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {...
1            [{"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 28, "name": "Action"}]
2              [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 80, "name": "Crime"}]
3       [{"id": 28, "name": "Action"}, {"id": 80, "name": "Crime"}, {"id": 18, "name": "Drama"}, {"id": ...
4       [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 878, "name": "Science Fic...
                                                       ...                                                 
4798            [{"id": 28, "name": "Action"}, {"id": 80, "name": "Crime"}, {"id": 53, "name": "Thriller"}]
4799                                       [{"id": 35, "name": "Comedy"}, {"id": 10749, "name": "Romance"}]
4800    [{"id": 35, "name": "Comedy"}, {"id": 18, "name": "Drama"}, {"id": 10749, "name": "Romance"}, {"...
4801                        

#### genres 칼럼은 문자열로 표기 되어 있어 문자열을 분해해 개별 장르를 파이썬 리스트 객체로 추출 필요

In [96]:
# 각 컬럼의 넓이를 최대로 100개 가져옴
pd.set_option('max_colwidth',100)
movies_df[['genres','keywords']][:10]

genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {...   
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 28, "name": "Action"}]   
2         [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 80, "name": "Crime"}]   
3  [{"id": 28, "name": "Action"}, {"id": 80, "name": "Crime"}, {"id": 18, "name": "Drama"}, {"id": ...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 878, "name": "Science Fic...   
5       [{"id": 14, "name": "Fantasy"}, {"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}]   
6                                   [{"id": 16, "name": "Animation"}, {"id": 10751, "name": "Family"}]   
7  [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 878, "name": "Science Fic...   
8    [{"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 10751, "name": "Family"}]   
9       [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}]   

                                                                                              keywords  
0  [{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "sp...  
1  [{"id": 270, "name": "ocean"}, {"id": 726, "name": "drug abuse"}, {"id": 911, "name": "exotic is...  
2  [{"id": 470, "name": "spy"}, {"id": 818, "name": "based on novel"}, {"id": 4289, "name": "secret...  
3  [{"id": 849, "name": "dc comics"}, {"id": 853, "name": "crime fighter"}, {"id": 949, "name": "te...  
4  [{"id": 818, "name": "based on novel"}, {"id": 839, "name": "mars"}, {"id": 1456, "name": "medal...  
5  [{"id": 851, "name": "dual identity"}, {"id": 1453, "name": "amnesia"}, {"id": 1965, "name": "sa...  
6  [{"id": 1562, "name": "hostage"}, {"id": 2343, "name": "magic"}, {"id": 2673, "name": "horse"}, ...  
7  [{"id": 8828, "name": "marvel comic"}, {"id": 9663, "name": "sequel"}, {"id": 9715, "name": "sup...  
8  [{"id": 616, "name": "witch"}, {"id": 2343, "name": "magic"}, {"id": 3872, "name": "broom"}, {"i...  
9  [{"id": 849, "name": "dc comics"}, {"id": 7002, "name": "vigilante"}, {"id": 9715, "name": "supe...

### 문자열을  리스트로 변환 literal_eval사용

In [97]:
from ast import literal_eval

movies_df['genres'] = movies_df['genres'].apply(literal_eval)
movies_df['keywords'] = movies_df['keywords'].apply(literal_eval)
movies_df[['genres','keywords']][:1]

genres  \
0  [{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {...   

                                                                                              keywords  
0  [{'id': 1463, 'name': 'culture clash'}, {'id': 2964, 'name': 'future'}, {'id': 3386, 'name': 'sp...

In [98]:
movies_df['genres'] = movies_df['genres'].apply(lambda x: [y['name'] for y in x])
movies_df['keywords'] =movies_df['keywords'].apply(lambda x: [y['name'] for y in x])
movies_df[['genres','keywords']][:1]

genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   

                                                                                              keywords  
0  [culture clash, future, space war, space colony, society, space travel, futuristic, romance, spa...

In [99]:
#countvectorizer 적용하기 위해 공백 문자로 word단위가 구분되는 문자열로 변환
df5 = movies_df[['genres','keywords']]
df5['genres'].apply(lambda x:(' ').join(x))

0       Action Adventure Fantasy Science Fiction
1                       Adventure Fantasy Action
2                         Action Adventure Crime
3                    Action Crime Drama Thriller
4               Action Adventure Science Fiction
                          ...                   
4798                       Action Crime Thriller
4799                              Comedy Romance
4800               Comedy Drama Romance TV Movie
4801                                            
4802                                 Documentary
Name: genres, Length: 4803, dtype: object

In [113]:
# movies_df['genres'] = ['Action','Drama','Romance']
m = movies_df.loc[(movies_df['genres']==('Action'))|(movies_df['genres']==('Romance'))]
m = movies_df.loc[(movies_df['vote_count']>10000)]
f =movies_df.loc[movies_df['genres']==[['Action','Romance']]]
f

ValueError: ('Lengths must match to compare', (4803,), (1, 2))

### 문서 유사도 측정을 위해서 genre를 문자열로 변경한 뒤 피처 벡터화한 행렬로 코사인 유사도 비교

In [101]:
from sklearn.feature_extraction.text import CountVectorizer

#CountVectorizer를 적용하기 위해 공백문자로 word 단위가 구분되는 문자열로 변환. 
# 연속된 문자열 변환 ('구분문자').join(리스트객체)
movies_df['genres_literal'] = movies_df['genres'].apply(lambda x : (' ').join(x))
count_vect = CountVectorizer(min_df=0, ngram_range=(1,2))
genre_mat = count_vect.fit_transform(movies_df['genres_literal'])
print(genre_mat.shape)

(4803, 276)


In [102]:
from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(genre_mat,genre_mat)
print(genre_sim.shape)
print(genre_sim)

(4803, 4803)
[[1.         0.59628479 0.4472136  ... 0.         0.         0.        ]
 [0.59628479 1.         0.4        ... 0.         0.         0.        ]
 [0.4472136  0.4        1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]


In [103]:
# 유사도 값이 높은 순으로 정렬된 행의 위치 인덱스 값 추출 
# 유사도가 높은 순으로 정렬된 타 레코드의 위치 인덱스 값
genre_sim_sorted_ind = genre_sim.argsort()[:,::-1]
print(genre_sim_sorted_ind[:10])

[[   0 3494  813 ... 3038 3037 2401]
 [ 262    1  129 ... 3069 3067 2401]
 [   2 1740 1542 ... 3000 2999 2401]
 ...
 [ 102 2995   56 ... 3046 3045 2401]
 [ 191  341  276 ... 3125 3124 2401]
 [  38   20  107 ... 3069 3067 2401]]


### 장르 콘텐츠 필터링을 이용한 영화 추천

In [104]:
def find_sim_movie(df,sorted_ind,title_name,top_n=10):
    #인자로 입력된 movie_df에서 title칼럼이 입력된 title_name값인 df추출
    title_movie = df[df['title']==title_name]
    # title_name을 가진 df의 index객체를 ndarray로 반환하고 sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n개 추출
    title_index= title_movie.index.values
    similar_indexes = sorted_ind[title_index,:(top_n)]
    # 추출된 top_n index 출력, top_n index는 2차원 데이터
    # df에서 index로 사용하기 위해 1차원 배열로 변경
    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)
    return df.iloc[similar_indexes]

In [105]:
similar_movies = find_sim_movie(movies_df,genre_sim_sorted_ind,'The Dark Knight',10)
similar_movies= similar_movies.loc[similar_movies['vote_count']>1000]
similar_movies[['title','vote_average','vote_count']]

[[  65 1281 2111 3828 3972 2229 4638 1041  308  273]]


title  vote_average  vote_count
65          The Dark Knight           8.2       12002
1041                Taken 2           6.1        2757
273   Gone in Sixty Seconds           6.1        1485

In [106]:
similar_movies[['title','vote_average','vote_count']].sort_values(by='vote_average',ascending=False)[:10]

title  vote_average  vote_count
65          The Dark Knight           8.2       12002
1041                Taken 2           6.1        2757
273   Gone in Sixty Seconds           6.1        1485

In [108]:
movies_df[['title','vote_average','vote_count']].sort_values(by='vote_average',ascending=False)[:10]

title  vote_average  vote_count
3519          Stiff Upper Lips          10.0           1
4247     Me You and Five Bucks          10.0           2
4045     Dancer, Texas Pop. 81          10.0           1
4662            Little Big Top          10.0           1
3992                 Sardaarji           9.5           2
2386            One Man's Hero           9.3           2
2970        There Goes My Baby           8.5           2
1881  The Shawshank Redemption           8.5        8205
2796     The Prisoner of Zenda           8.4          11
3337             The Godfather           8.4        5893

[과제] 아래사항을 수행하세요

장르 콘텐츠 필터링을 이용한 영화 추천(count 방식으로 feature 벡터화, cosine_similarity로 유사도 측정)  
평점에 평가 횟수를 반영하여 새롭게 평점 기준을 정의한 후 적용하여 영화 추천(vote_count를 포함하여 아래 가중평점 사용)  
m값은 평점 투표 횟수가 많은 영화에 더 많은 가중 평점을 부여  
m값은 전체 투표 횟수에서 상위 60%에 해당하는 횟수를 기준으로 정함  
가중평점 : (v/(v+m))R + (m/(v+m))C  
v : 개별 영화에 평점을 투표한 횟수  
m : 평점을 부여하기 위한 최소 투표 횟수  
R : 개별 영화에 대한 평균 평점  
C : 전체 영화에 대한 평균 평점  

In [ ]:
# c -> 전체 영화에 대한 평균 평점, m -> 평점을 부여하기 위한 최소 투표 횟수
C =movies_df['vote_average'].mean()
#전체 투표 횟수에서 상위 60%에 해당하는 횟수 기준
m = movies_df['vote_count'].quantile(0.6)
print('C:',round(C,3),'m:',round(m,3))

In [ ]:
percentile = 0.6
C =movies_df['vote_average'].mean()
m = movies_df['vote_count'].quantile(0.6)

def weighted_vote_average(record):
    v = record['vote_count']
    R = record['vote_average']
    return ( (v/(v+m)) *R) + ( (m/(m+v)) * C)
movies_df['weighted_vote'] = movies_df.apply(weighted_vote_average,axis=1)

In [ ]:
movies_df[['title','vote_average','weighted_vote','vote_count']].sort_values('weighted_vote',ascending=False)[:10]

In [ ]:
def find_sim_movie(df,sorted_ind,title_name,top_n=10):
    title_movie = df[df['title']==title_name]
    title_index= title_movie.index.values
    # top_n의 2배수에 해당하는 장르 유사성이 높은 인덱스 추출
    similar_indexes = sorted_ind[title_index,:(top_n*2)]
    similar_indexes = similar_indexes.reshape(-1)
    #기준 영화 인덱스는 제외
    similar_indexes = similar_indexes[similar_indexes !=title_index]
    return df.iloc[similar_indexes].sort_values('weighted_vote',ascending=False)[:top_n]

In [ ]:
silmiar_moives= find_sim_movie(movies_df,genre_sim_sorted_ind,"The Dark Knight",10)
silmiar_moives[['title','vote_average','weighted_vote']]