## Python Numpy 선형대수

- 단위행렬 (Unit matrix): np.eye(n)
- 대각행렬 (Diagonal matrix): np.diag(x)
- 내적 (Dot product, Inner product): np.dot(a, b)
- 대각합 (Trace): np.trace(x)
- 행렬식 (Matrix Determinant): np.linalg.det(x)
- 역행렬 (Inverse of a matrix): np.linalg.inv(x)
- 고유값 (Eigenvalue), 고유벡터 (Eigenvector): w, v = np.linalg.eig(x)
- 특이값 분해 (Singular Value Decomposition): u, s, vh = np.linalg.svd(A)
- 연립방정식 해 풀기 (Solve a linear matrix equation): np.linalg.solve(a, b)
- 최소자승 해 풀기 (Compute the Least-squares solution): m, c = np.linalg.lstsq(A, y, rcond=None)[0]

https://rfriend.tistory.com/380


In [1]:
#정방행렬/정사각형 행렬:  같은 수의 행과 열을 갖는 행렬 (n*n 행렬)
import numpy as np
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [2]:
# 대각 정방행렬: 주대각선 원소외에 모두 0인 정방행렬
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [3]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [4]:
#항등행렬: 단위행렬(unit matrix)라고도 하며 주대각선 원소가 모두 1이고 나머지 원소는 모두 0인 정방행렬
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.diag([1,1,1])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 벡터와 행렬의 연산
- 벡터/행렬의 덧셈과 뺄셈 : 같은 위치에 있는 원소끼리 수행. 요소별 연산
- 스칼라와 벡터/행렬의 곱셈
- 브로드캐스팅 : 스칼라를 벡터로 변환한 연산을 허용
- 벡터와 벡터의 곱셈. 내적
 - 두 벡터의 차원(길이)이 같아야 한다.
 - 앞의 벡터가 행벡터이고 위의 벡터가 열벡터여야 한다.
 - 내적의 결과는 스칼라 값이 됨. dot() 또는 @ 연산자로 계산


스칼라:방향이 없는 숫자값 (온도)
벡터: 방향과 크기가 존재하는 숫자값 (속도)
행렬: 시리즈가 여러개인거 매트릭스가 됬잖아   
5 스칼라  
[1,2,3] 벡터  
[[1,2,3],[2,3,4]] 행렬

In [ ]:
텐서는 임의의 기하 구조를 좌표 독립(座標獨立, coordinate independent)적으로 표현하기 위한 표기법이다
0차원,1차원,2차원 다 텐서야
